#!/bin/bash

set -e
cd "$(dirname "$0")"/../..

# Clone poppler dir from main portage tree
pre=( app-text/poppler/*.ebuild )
rm -r app-text/poppler
cp -r "${PORTDIR:-/usr/portage}/app-text/poppler" app-text/

# Make adjustments to ebuilds
sed -i \
    -e 's/^\(IUSE=.*\) qt4/\1 qt3 qt4/' \
    -e 's/-DWITH_Qt3=OFF/$(cmake-utils_use_with qt3)/' \
    -e 's/^\([ \t]*\)\(qt4? (\)/\1qt3? ( >=x11-libs\/qt-3.3:3 )\n\1\2/' \
    -e 's/^\(inherit.*\)/\1 qt3/' \
    app-text/poppler/*.ebuild

# Drop all unmodified ebuilds, e.g. for older versions without qt4 USE flag
for i in app-text/poppler/*.ebuild; do
    cmp -s "$i" "${PORTDIR:-/usr/portage}/$i" && rm $i
done

# Redigest and show difference
ebuild $(ls -1 app-text/poppler/*.ebuild | tail -n1) digest
diff -ur "${PORTDIR:-/usr/portage}/app-text/poppler" app-text/poppler || true
Documentation/maintainers/generate_unmask

git add app-text/poppler/{*.ebuild,ChangeLog,Manifest} \
    Documentation/package.unmask/kde-3.5
for old in "${pre[@]}"; do
	test -e "${old}" || git rm "${old}"
done
git status
echo 'Run: git commit -m "[app-text/poppler] Update from main portage tree"'
